language: python
cache: pip
dist: xenial

matrix:
  include:
  - env: TOXENV=py34-dj111
    python: 3.4
  - env: TOXENV=py35-dj111
    python: 3.5
  - env: TOXENV=py36-dj111
    python: 3.6
  - env: TOXENV=py37-dj2
    python: 3.7
  - env: TOXENV=py38-dj21
    python: 3.8
  - env: TOXENV=py38-dj22
    python: 3.8

install:
- pip install tox codecov
script:
- tox
after_success:
- codecov --token=d1c52f52-bbc0-4eeb-b7dd-e4ac89504b93
deploy:
  provider: pypi
  user: ababic
  distributions: sdist bdist_wheel
  password: ${PYPI_PASSWORD}
  on:
    tags: true
    branch: master
    repo: ababic/django-cogwheels
    condition: "$TOXENV = py37-dj21"
